# Generated by Django 4.1.7 on 2023-03-29 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(default='Manager', max_length=255)),
                ('start_date', models.DateField()),
                ('groups', models.ManyToManyField(blank=True, to='auth.group')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='planner.location')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams_managed_by', to='planner.location')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='planner.manager')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(default='Member', max_length=255)),
                ('start_date', models.DateField()),
                ('groups', models.ManyToManyField(blank=True, to='auth.group')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='planner.location')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='planner.manager')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='planner.team')),
            ],
        ),
    ]
